spring:
  datasource:
    url: jdbc:h2:mem:apiVideos
    username: sa
    password:
    driverClassName: org.h2.Driver

jpa:
  database-platform: org.hibernate.dialect.
  properties.hibernate.show_sql: true
  properties.hibernate.format_sql: true

h2:
  console:
    enabled: true
    path: /h2